#!/bin/sh

export PATH=/bin:/sbin

echo "### USING UPDATED INIT ###"

# Mount kernel filesystems
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys

echo "Bringing up network..."

/bin/busybox ip link set eth0 up
/bin/busybox udhcpc -i eth0

echo "Network is up"

exec /bin/busybox sh

